name: World Of Dan
favicon: null
layout_spectrum: 0.4991
typography_spectrum: 0.41215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0
  saturation: 0.48644770379178226
  rhythmicContrast: 0.7055628255475312
purpose: []
